"""image_url_increase

Revision ID: 0700e65e3aa0
Revises: 8c4deca24ddd
Create Date: 2020-04-09 19:34:12.797963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0700e65e3aa0'
down_revision = '8c4deca24ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=2083),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'image_file',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
